server:
  port: 8083

spring:
    application:
        name: accountmovement-microservice
    data:
        mongodb:
            host: localhost
            port: 27017
            database: AccountMovement1